import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import request from 'supertest';
import {createApp} from '../src/app.js';
import {hashPassword} from '../src/auth.js';

test('authenticated work flow protects private fields and validates transitions',async()=>{
 const db=new PGlite();await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 // A serialized pool adapter for embedded Postgres; production uses pg.Pool.
 let tail=Promise.resolve();
 async function lock(){let unlock;const previous=tail;tail=new Promise(r=>unlock=r);await previous;return unlock;}
 const run=async(sql,args)=>{const r=await db.query(sql,args);return {...r,rowCount:Math.max(r.affectedRows??0,r.rows.length)};};
 const pool={query:async(sql,args)=>{const done=await lock();try{return await run(sql,args);}finally{done();}},
   connect:async()=>{const done=await lock();return {query:run,release:done};}};
 const app=createApp(pool,()=>{},{testing:true});
 const api=request(app);
 const account=async(email)=>{
   await pool.query("insert into users(id,email,password_hash,store_number,site_lat,site_lng,site_address) values($1,$2,$3,'007',24.5,46.7,'Private pinned work site')",[randomUUID(),email,await hashPassword('StrongPassword123')]);
   const r=await api.post('/auth/login').send({email,password:'StrongPassword123'});assert.equal(r.status,200);return r.body;
 };
 try {
 const adminPage=await api.get('/');
 assert.equal(adminPage.status,200);assert.match(adminPage.text,/Buklin Admin/);
 const mapApp=await api.get('/app/');
 assert.equal(mapApp.status,200);
 // OSM requires a Referer on browser tile requests. Send only the origin
 // cross-site, preserving the admin panel's more restrictive policy.
 assert.equal(mapApp.headers['referrer-policy'],'strict-origin-when-cross-origin');
 assert.equal(adminPage.headers['referrer-policy'],'strict-origin-when-cross-origin');
 assert.match(adminPage.headers['content-security-policy'],/https:\/\/tile.openstreetmap.org/);
 assert.equal((await api.get('/health')).status,200);
 assert.equal((await api.post('/auth/register').send({email:'blocked@example.com',password:'StrongPassword123'})).status,403);
 const customer=await account('customer@example.com');
 const stranger=await account('stranger@example.com');
 const operator=await account('operator@example.com');
 const other=await account('other@example.com');
 const admin=await account('admin@example.com');
 await pool.query("update users set role='admin' where id=$1",[admin.user.id]);
 await pool.query("update users set phone='+966501112233' where id=$1",[customer.user.id]);
 await pool.query("update users set role='operator',service='Pickup van',online=true where id in ($1,$2)",[operator.user.id,other.user.id]);
 // Availability belongs to the operator, independently of a login session.
 const operatorSession=await api.post('/auth/login').send({email:'operator@example.com',password:'StrongPassword123',expected_role:'operator'});
 assert.equal((await api.post('/auth/logout').auth(operatorSession.body.token,{type:'bearer'}).send({})).status,200);
 assert.equal((await api.get('/jobs').auth(operator.token,{type:'bearer'})).body.online,true);
 assert.equal((await api.post('/auth/login').send({email:'customer@example.com',password:'StrongPassword123',expected_role:'customer'})).status,200);
 assert.equal((await api.post('/auth/login').send({email:'customer@example.com',password:'StrongPassword123',expected_role:'operator'})).status,401);
 assert.equal((await api.post('/auth/login').send({email:'operator@example.com',password:'StrongPassword123',expected_role:'operator'})).status,200);
 assert.equal((await api.post('/auth/login').send({email:'operator@example.com',password:'StrongPassword123',expected_role:'customer'})).status,401);
 assert.equal((await api.post('/auth/login').send({email:'customer@example.com',password:'StrongPassword123',admin_only:true})).status,401);
 assert.equal((await api.post('/auth/login').send({email:'admin@example.com',password:'StrongPassword123',admin_only:true})).status,200);
 const body={equipment:'Pickup van',loading:'Dyna',store_number:'007',offered_amount:'250',
   site_address:'Private pinned work site',work_details:'Pickup van with Dyna loading',lat:24.5,lng:46.7};
 const post=(path,token,data)=>api.post(path).auth(token,{type:'bearer'}).send(data);
 const get=(path,token)=>api.get(path).auth(token,{type:'bearer'});
 const newAccount={name:'Test Operator',phone:'+966501234567',username:'new_operator',password:'NewPassword123',role:'operator',service:'Big truck'};
 assert.equal((await post('/admin/users',customer.token,newAccount)).status,403);
 assert.equal((await post('/admin/users',operator.token,newAccount)).status,403);
 assert.equal((await get('/admin/users',customer.token)).status,403);
 for(const invalid of [{service:null},{service:'Dyna'},{phone:'abc'},{username:'x'},{password:'short'},{role:'admin'},{role:'customer'}]) {
   assert.equal((await post('/admin/users',admin.token,{...newAccount,...invalid})).status,400);
 }
 for(const [index,service] of ['5-finger excavator grapple','Pickup van','Big truck'].entries()) {
   const createdUser=await post('/admin/users',admin.token,{...newAccount,username:'machine_'+index,service});
   assert.equal(createdUser.status,201);assert.equal(createdUser.body.user.service,service);
   assert.equal(createdUser.body.user.password,undefined);assert.equal(createdUser.body.user.password_hash,undefined);
 }
 const customerCreated=await post('/admin/users',admin.token,{...newAccount,role:'customer',service:null,store_number:'007',site_lat:24.5,site_lng:46.7,site_address:'Private pinned work site',username:'new_customer'});
 assert.equal(customerCreated.status,201);assert.equal(customerCreated.body.user.service,null);
 const loggedIn=await api.post('/auth/login').send({email:'NEW_CUSTOMER',password:newAccount.password});
 assert.equal(loggedIn.status,200);assert.equal(loggedIn.body.user.role,'customer');
 assert.equal(loggedIn.body.user.store_number,'007');
 assert.equal(loggedIn.body.user.site_lat,24.5);
 assert.equal(loggedIn.body.user.site_lng,46.7);
 assert.equal((await get('/me',loggedIn.body.token)).body.site_address,'Private pinned work site');
 const customerInput={...newAccount,role:'customer',service:null,store_number:'007',site_lat:24.5,site_lng:46.7,site_address:'Private pinned work site',username:'invalid_location'};
 for(const invalid of [{site_lat:undefined},{site_lng:undefined},{site_address:undefined},{site_lat:91},{site_lng:-181},{site_lat:null},{site_address:''}]) {
   assert.equal((await post('/admin/users',admin.token,{...customerInput,...invalid})).status,400);
 }
 for(const invalid of [{lat:25},{lng:47},{site_address:'Different location'}]) {
   assert.equal((await post('/jobs',customer.token,{...body,...invalid})).status,400);
 }
 await pool.query('update users set site_lat=null,site_lng=null,site_address=null where id=$1',[stranger.user.id]);
 assert.equal((await post('/jobs',stranger.token,body)).status,403);
 const assignLocationPath=`/admin/users/${stranger.user.id}/location`;
 const fixedLocation={site_lat:24.5,site_lng:46.7,site_address:'Private pinned work site'};
 assert.equal((await post(assignLocationPath,customer.token,fixedLocation)).status,403);
 assert.equal((await post(assignLocationPath,admin.token,{...fixedLocation,site_lat:91})).status,400);
 assert.equal((await post(assignLocationPath,admin.token,fixedLocation)).status,200);
 assert.equal((await post(assignLocationPath,admin.token,{...fixedLocation,site_lat:25})).status,409);
 assert.equal((await get('/jobs',stranger.token)).body.site_lat,24.5);
 assert.equal((await get('/me',loggedIn.body.token)).body.store_number,'007');
 for(const store_number of [undefined,null,'','12','abc']) {
   assert.equal((await post('/admin/users',admin.token,{...newAccount,role:'customer',service:null,store_number,username:'invalid_store'})).status,400);
 }
 assert.equal((await post('/jobs',customer.token,{...body,store_number:'999'})).status,400);
 await pool.query('update users set store_number=null where id=$1',[stranger.user.id]);
 assert.equal((await post('/jobs',stranger.token,body)).status,403);
 const assignStorePath=`/admin/users/${stranger.user.id}/store-number`;
 assert.equal((await post(assignStorePath,customer.token,{store_number:'007'})).status,403);
 assert.equal((await post(assignStorePath,admin.token,{store_number:'7'})).status,400);
 assert.equal((await post(assignStorePath,admin.token,{store_number:'007'})).status,200);
 assert.equal((await post(assignStorePath,admin.token,{store_number:'008'})).status,409);
 assert.equal((await get('/jobs',stranger.token)).body.store_number,'007');
 assert.equal((await post('/admin/users',admin.token,{...newAccount,username:'new_customer'})).status,409);
 const directory=await get('/admin/users',admin.token);
 assert.equal(directory.status,200);
 assert.ok(directory.body.users.every(u=>!('password_hash' in u) && !('password' in u)));
 for(const invalid of [{store_number:''},{store_number:'12'},{offered_amount:'0'},{offered_amount:'1.234'},
   {offered_amount:'29'},{offered_amount:'1000'},{offered_amount:'250.50'},{offered_amount:'007'},{loading:'Custom'},{lat:91}]) {
   assert.equal((await post('/jobs',customer.token,{...body,...invalid})).status,400);
 }
 assert.equal((await api.get('/jobs')).status,401);
 const customerDebtPath=`/admin/users/${customer.user.id}/balance`;
 assert.equal((await post(customerDebtPath,admin.token,{id:randomUUID(),amount:-20,reason:'Unpaid fees'})).status,200);
 const customerPaymentRequired=await post('/jobs',customer.token,body);
 assert.equal(customerPaymentRequired.status,403);assert.match(customerPaymentRequired.body.error,/Payment required/);
 assert.equal((await get('/jobs',customer.token)).body.payment_required,true);
 assert.equal((await post(customerDebtPath,admin.token,{id:randomUUID(),amount:20,reason:'Payment received',kind:'payment'})).status,200);
 const {store_number: ignoredStore,lat: ignoredLat,lng: ignoredLng,site_address: ignoredAddress,...fixedStoreRequest}=body;
 const created=await post('/jobs',customer.token,fixedStoreRequest);assert.equal(created.status,201);
 const id=created.body.id;
 const storedSite=await pool.query('select * from job_sites where job_id=$1',[id]);
 assert.equal(storedSite.rows[0].lat,24.5);
 assert.equal(storedSite.rows[0].lng,46.7);
 assert.equal(storedSite.rows[0].address,'Private pinned work site');
 assert.equal((await post('/jobs',customer.token,body)).status,409);
 const operatorDebtPath=`/admin/users/${operator.user.id}/balance`;
 assert.equal((await post(operatorDebtPath,admin.token,{id:randomUUID(),amount:-20,reason:'Unpaid fees'})).status,200);
 assert.equal((await get('/jobs',operator.token)).body.jobs.length,0);
 const operatorPaymentRequired=await post(`/jobs/${id}/action`,operator.token,{action:'accept'});
 assert.equal(operatorPaymentRequired.status,403);assert.match(operatorPaymentRequired.body.error,/Payment required/);
 assert.equal((await api.put('/availability').auth(operator.token,{type:'bearer'}).send({available:true})).status,403);
 assert.equal((await post(operatorDebtPath,admin.token,{id:randomUUID(),amount:20,reason:'Payment received',kind:'payment'})).status,200);
 const offersResponse=await get('/jobs',operator.token);assert.equal(offersResponse.status,200,JSON.stringify(offersResponse.body));
 const offers=offersResponse.body.jobs;
 assert.equal(offers[0].store_number,null);assert.equal(offers[0].address,null);
 assert.equal(offers[0].offered_amount,'250.00');assert.equal(offers[0].site_lat,undefined);
 assert.equal((await get(`/jobs/${id}/location`,operator.token)).status,404);
 assert.equal((await get('/jobs',stranger.token)).body.jobs.length,0);
 const competing=await Promise.all([operator,other].map(u=>post(`/jobs/${id}/action`,u.token,{action:'accept'})));
 assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);
 const winner=competing[0].status===200?operator:other;
 const loser=winner===operator?other:operator;
 assert.ok(!(await get('/jobs',loser.token)).body.jobs.some(job=>job.id===id));
 const accepted=(await get('/jobs',winner.token)).body.jobs[0];
 assert.equal(accepted.start_otp,null);
 assert.equal(accepted.customer_phone,null);
 const customerJob=(await get('/jobs',customer.token)).body.jobs[0];
 assert.match(customerJob.start_otp,/^[0-9]{4}$/);
 const otp=customerJob.start_otp;
 assert.equal(accepted.store_number,'007');assert.equal(accepted.address,body.site_address);
 assert.equal((await get(`/jobs/${id}/location`,loser.token)).status,404);
 assert.equal((await post(`/jobs/${id}/action`,loser.token,{action:'cancel'})).status,409);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'complete'})).status,409);
 assert.equal((await api.put(`/jobs/${id}/location`).auth(loser.token,{type:'bearer'}).send({lat:1,lng:2})).status,403);
 assert.equal((await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:24.6,lng:46.8})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.jobs[0].customer_phone,null);
 assert.equal((await get(`/jobs/${id}/location`,customer.token)).body.position.lat,24.6);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'travel'})).status,200);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp})).status,409);
 await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:body.lat,lng:body.lng});
 assert.equal((await get('/jobs',winner.token)).body.jobs[0].customer_phone,'+966501112233');
 await pool.query("update job_locations set updated_at=now()-interval '1 minute' where job_id=$1",[id]);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp})).status,409);
 await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:body.lat,lng:body.lng});
 const wrong=otp==='0000'?'0001':'0000';
 for(let i=0;i<5;i++) assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp:wrong})).status,400);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp})).status,429);
 await pool.query("update job_start_codes set window_started=now()-interval '2 minutes' where job_id=$1",[id]);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp})).status,200);
 assert.equal((await post(`/jobs/${id}/action`,customer.token,{action:'cancel'})).status,409);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'cancel'})).status,409);
 assert.equal((await get('/jobs',customer.token)).body.jobs[0].start_otp,null);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'start',otp})).status,409);
 const nextJob=await post('/jobs',stranger.token,body);assert.equal(nextJob.status,201);
 assert.ok((await get('/jobs',winner.token)).body.jobs.every(j=>j.status!=='requested'));
 assert.equal((await post(`/jobs/${nextJob.body.id}/action`,winner.token,{action:'accept'})).status,409);
 await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:1,lng:2});
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'complete'})).status,409);
 await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:body.lat,lng:body.lng});
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'complete'})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.online,true);
 // An explicit switch-off persists across refreshes and prevents acceptance.
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:false})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.online,false);
 assert.equal((await post(`/jobs/${nextJob.body.id}/action`,winner.token,{action:'accept'})).status,409);
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:true})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.jobs.find(job=>job.id===id).customer_phone,null);
 assert.equal((await get('/jobs',customer.token)).body.balance,-3);
 assert.equal((await get('/jobs',winner.token)).body.balance,-3);
 assert.equal((await get('/jobs',stranger.token)).body.balance,0);
 assert.equal((await post(`/jobs/${id}/action`,winner.token,{action:'complete'})).status,409);
 assert.equal((await get('/jobs',customer.token)).body.balance,-3);
 assert.equal((await get('/jobs',winner.token)).body.balance,-3);
 assert.ok((await get('/jobs',winner.token)).body.jobs.some(j=>j.id===nextJob.body.id));
 assert.equal((await api.put(`/jobs/${id}/location`).auth(winner.token,{type:'bearer'}).send({lat:1,lng:2})).status,403);
 assert.equal((await get(`/jobs/${id}/location`,customer.token)).status,404);
 await post('/auth/logout',customer.token,{});
 assert.equal((await post(`/jobs/${nextJob.body.id}/action`,winner.token,{action:'accept'})).status,200);
 assert.equal((await post(`/jobs/${nextJob.body.id}/action`,stranger.token,{action:'cancel'})).status,200);
 const blockedCustomer=(await get('/jobs',stranger.token)).body;
 assert.ok(new Date(blockedCustomer.blocked_until)-Date.now()>71*3600000);
 assert.equal(blockedCustomer.balance,-2);
 assert.equal((await post('/jobs',stranger.token,body)).status,403);
 await pool.query("update users set blocked_until=now()-interval '1 second' where id=$1",[stranger.user.id]);
 const another=await post('/jobs',stranger.token,body);assert.equal(another.status,201);
 assert.equal((await post(`/jobs/${another.body.id}/action`,winner.token,{action:'accept'})).status,200);
 assert.equal((await post(`/jobs/${another.body.id}/action`,winner.token,{action:'travel'})).status,200);
 assert.equal((await post(`/jobs/${another.body.id}/action`,winner.token,{action:'cancel'})).status,200);
 const blockedOperator=(await get('/jobs',winner.token)).body;
 assert.equal(blockedOperator.online,true);
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:false})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.online,false);
 assert.ok(new Date(blockedOperator.blocked_until)-Date.now()>4.9*3600000);
 assert.equal(blockedOperator.balance,-5);
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:true})).status,403);
 const retry=await post('/jobs',stranger.token,body);assert.equal(retry.status,201);
 assert.ok((await get('/jobs',winner.token)).body.jobs.every(j=>j.status!=='requested'));
 assert.notEqual((await post(`/jobs/${retry.body.id}/action`,winner.token,{action:'accept'})).status,200);
 await pool.query("update users set blocked_until=now()-interval '1 second' where id=$1",[winner.user.id]);
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:true})).status,200);
 assert.equal((await post(`/jobs/${retry.body.id}/action`,winner.token,{action:'accept'})).status,200);
 assert.equal((await get('/jobs',customer.token)).status,401);
 const adjustment={id:randomUUID(),amount:5,reason:'Payment received'};
 const balancePath=`/admin/users/${winner.user.id}/balance`;
 assert.equal((await post(balancePath,stranger.token,adjustment)).status,403);
 assert.equal((await post(balancePath,winner.token,adjustment)).status,403);
 assert.equal((await post(balancePath,admin.token,adjustment)).status,200);
 assert.equal((await post(balancePath,admin.token,adjustment)).status,200);
 assert.equal((await get('/jobs',winner.token)).body.balance,0);
 assert.equal((await post(balancePath,admin.token,{...adjustment,amount:6})).status,409);
 assert.equal((await post(balancePath,admin.token,{id:randomUUID(),amount:-2,reason:'Correction'})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.balance,-2);
 assert.equal((await get(balancePath,admin.token)).body.entries.length,winner===operator?6:4);
 assert.equal((await get(balancePath,stranger.token)).status,403);
 assert.equal((await post(`/admin/users/${customer.user.id}/balance`,admin.token,{id:randomUUID(),amount:3,reason:'Customer payment'})).status,200);
 assert.equal((await get('/admin/users',admin.token)).body.users.find(u=>u.id===customer.user.id).balance,0);
 await pool.query("update users set blocked_until=now()+interval '5 hours' where id=$1",[winner.user.id]);
 assert.equal((await post(`/admin/users/${winner.user.id}/clear-restriction`,stranger.token,{})).status,403);
 assert.equal((await post(`/admin/users/${winner.user.id}/clear-restriction`,admin.token,{})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.blocked_until,null);
 // Available funds pay the completion fee before the balance becomes debt.
 assert.equal((await post(balancePath,admin.token,{id:randomUUID(),amount:22,reason:'Wallet top up'})).status,200);
 assert.equal((await post(`/admin/users/${stranger.user.id}/balance`,admin.token,{id:randomUUID(),amount:20,reason:'Wallet top up'})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.balance,20);
 assert.equal((await get('/jobs',stranger.token)).body.balance,18);
 const finalJob=retry.body.id;
 await api.put(`/jobs/${finalJob}/location`).auth(winner.token,{type:'bearer'}).send({lat:body.lat,lng:body.lng});
 assert.equal((await post(`/jobs/${finalJob}/action`,winner.token,{action:'travel'})).status,200);
 const finalOtp=(await get('/jobs',stranger.token)).body.jobs.find(j=>j.id===finalJob).start_otp;
 assert.equal((await post(`/jobs/${finalJob}/action`,winner.token,{action:'start',otp:finalOtp})).status,200);
 assert.equal((await post(`/jobs/${finalJob}/action`,winner.token,{action:'complete'})).status,200);
 assert.equal((await get('/jobs',winner.token)).body.balance,17);
 assert.equal((await get('/jobs',stranger.token)).body.balance,15);
 const reinstalledCustomer=await api.post('/auth/login').send({email:'customer@example.com',password:'StrongPassword123',expected_role:'customer'});
 assert.equal(reinstalledCustomer.status,200);
 assert.ok((await get('/jobs',reinstalledCustomer.body.token)).body.jobs.some(job=>job.id===id&&job.status==='completed'));
 assert.equal((await get('/admin/dashboard',stranger.token)).status,403);
 assert.equal((await get('/admin/dashboard',winner.token)).status,403);
 assert.equal((await post(balancePath,admin.token,{id:randomUUID(),amount:7,reason:'Cash received',kind:'payment'})).status,200);
 assert.equal((await post(balancePath,admin.token,{id:randomUUID(),amount:3,reason:'Courtesy credit',kind:'adjustment'})).status,200);
 const workHistory=await get(`/admin/users/${winner.user.id}/jobs`,admin.token);
 assert.equal(workHistory.status,200);assert.equal(workHistory.body.completed,2);assert.ok(workHistory.body.total>=2);
 assert.equal((await get(`/admin/users/${winner.user.id}/jobs`,stranger.token)).status,403);
 const exactBalance={id:randomUUID(),balance:25,reason:'Admin balance correction'};
 assert.equal((await post(`/admin/users/${winner.user.id}/balance/set`,stranger.token,exactBalance)).status,403);
 assert.equal((await post(`/admin/users/${winner.user.id}/balance/set`,admin.token,exactBalance)).status,200);
 assert.equal((await get('/jobs',winner.token)).body.balance,25);
 assert.equal((await api.delete(`/admin/users/${customerCreated.body.user.id}`).auth(stranger.token,{type:'bearer'})).status,403);
 assert.equal((await api.delete(`/admin/users/${customerCreated.body.user.id}`).auth(admin.token,{type:'bearer'})).status,200);
 assert.equal((await get('/me',loggedIn.body.token)).status,401);
 assert.ok(!(await get('/admin/users',admin.token)).body.users.some(u=>u.id===customerCreated.body.user.id));
 assert.equal((await pool.query('select id from users where id=$1',[customerCreated.body.user.id])).rowCount,0);
 assert.equal((await get(`/admin/users/${customerCreated.body.user.id}/jobs`,admin.token)).status,404);
 assert.equal((await post('/admin/users',admin.token,{...newAccount,role:'customer',service:null,store_number:'007',site_lat:24.5,site_lng:46.7,site_address:'Private pinned work site',username:'new_customer'})).status,201);
 const dashboard=(await get('/admin/dashboard',admin.token)).body;
 assert.equal(Number(dashboard.totals.received),47);
 assert.equal(Number(dashboard.totals.fees),16);
 assert.equal(Number(dashboard.totals.completed_jobs),2);
 assert.equal(Number(dashboard.totals.total_requests),4);
 assert.ok(Number(dashboard.totals.online_operators)>=1);
 assert.ok(dashboard.activities.some(a=>a.description==='Work status: completed'));
 assert.ok(dashboard.activities.some(a=>a.description.includes('Cash received')));
 assert.equal((await post(balancePath,admin.token,{id:randomUUID(),amount:-3,reason:'Invalid payment',kind:'payment'})).status,400);
 // References are stable and unique; history expiry never changes billing.
 const numbered=await pool.query('select request_number,closed_at from jobs');
 assert.equal(new Set(numbered.rows.map(j=>String(j.request_number))).size,numbered.rows.length);
 assert.ok(numbered.rows.every(j=>Number(j.request_number)>=10001));
 assert.ok((await pool.query('select closed_at from jobs where id=$1',[finalJob])).rows[0].closed_at);
 await pool.query("update jobs set closed_at=now()-interval '71 hours' where id=$1",[finalJob]);
 assert.ok((await get('/jobs',winner.token)).body.jobs.some(j=>j.id===finalJob));
 await pool.query("update jobs set closed_at=now()-interval '73 hours' where id=$1",[finalJob]);
 assert.ok(!(await get('/jobs',winner.token)).body.jobs.some(j=>j.id===finalJob));
 assert.ok(!(await get('/jobs',stranger.token)).body.jobs.some(j=>j.id===finalJob));
 assert.equal((await get('/jobs',winner.token)).body.balance,25);
 assert.ok((await pool.query('select id from jobs where id=$1',[finalJob])).rows.length);
 // Applying the schema again must not renumber requests or reset their expiry.
 const before=await pool.query('select request_number,closed_at from jobs where id=$1',[finalJob]);
 await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 assert.deepEqual((await pool.query('select request_number,closed_at from jobs where id=$1',[finalJob])).rows,before.rows);
 // Permanent deletion cancels live work, removes the user, and preserves the other participant's history and balance.
 const deletionJob=await post('/jobs',reinstalledCustomer.body.token,body);
 assert.equal(deletionJob.status,201);
 assert.equal((await api.put('/availability').auth(winner.token,{type:'bearer'}).send({available:true})).status,200);
 assert.equal((await post(`/jobs/${deletionJob.body.id}/action`,winner.token,{action:'accept'})).status,200);
 assert.equal((await api.delete(`/admin/users/${admin.user.id}`).auth(admin.token,{type:'bearer'})).status,404);
 assert.equal((await api.delete(`/admin/users/${customer.user.id}`).auth(admin.token,{type:'bearer'})).status,200);
 assert.equal((await pool.query('select id from users where id=$1',[customer.user.id])).rowCount,0);
 assert.equal((await get('/me',reinstalledCustomer.body.token)).status,401);
 const remainingWork=(await get('/jobs',winner.token)).body;
 assert.equal(remainingWork.balance,25);
 assert.ok(remainingWork.jobs.some(j=>j.id===deletionJob.body.id&&j.status==='cancelled'&&j.customer_id===null));
 assert.ok(remainingWork.jobs.some(j=>j.id===id&&j.status==='completed'));
 assert.equal((await pool.query('select * from job_start_codes where job_id=$1',[deletionJob.body.id])).rowCount,0);
 assert.equal((await pool.query('select * from notification_outbox where job_id=$1',[deletionJob.body.id])).rowCount,0);
 const strangerBalance=(await get('/jobs',stranger.token)).body.balance;
 assert.equal((await api.delete(`/admin/users/${winner.user.id}`).auth(admin.token,{type:'bearer'})).status,200);
 assert.equal((await pool.query('select id from users where id=$1',[winner.user.id])).rowCount,0);
 assert.equal((await get('/jobs',stranger.token)).body.balance,strangerBalance);
 assert.equal((await pool.query('select operator_id from jobs where id=$1',[finalJob])).rows[0].operator_id,null);
 }finally{await db.close();}
});
